import { ThemeProvider } from '@/app/context/ThemeContext';
import { Footer } from '@/components/Footer/Footer';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { CallModalProvider } from './context/CallModalContext';
import { LanguageProvider } from './context/LanguageContext';
import './globals.scss';

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
	weight: ['400', '700'],
});

// const geistMono = Geist_Mono({
// 	variable: '--font-geist-mono',
// 	subsets: ['latin'],
// });

export const metadata: Metadata = {
	title: 'MB patisserie',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={montserrat.variable}>
				<ThemeProvider>
					<LanguageProvider>
						<CallModalProvider>{children}</CallModalProvider>
						<Footer />
					</LanguageProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
